GET http://localhost:5001/api/v1/staff/courses

###
POST  http://localhost:5001/api/v1/auth/login
Content-Type: application/json

{
  "email": "phamtrungnam@fpt.edu.vn",
  "password": "ILoveMyWife"
}

###

GET http://localhost:5001/api/v1/staff/trainer/view

###
POST http://localhost:5001/api/v1/staff/auth/register
Content-Type: application/json

{
  "email": "phamtrungnam@fpt.edu.vn",
  "password": "ILoveMyWife",
  "fullname": "Pham Trung Nam",
  "age": 26,
  "role": "Trainer",
  "specialty": "IT and Development"
}

###
POST http://localhost:5001/api/v1/staff/auth/register
Content-Type: application/json

{
  "email": "dangtieubinh@fpt.edu.vn",
  "password": "ILoveMyWife",
  "fullname": "Dang Tieu Binh",
  "role": "Trainer",
  "age": 32,
  "specialty": "Economic PhD"
}

###
POST http://localhost:5001/api/v1/staff/auth/register
Content-Type: application/json

{
  "email": "nguyenhoanglam.emily@gmail.com",
  "password": "dontbesad",
  "fullname": "Nguyen Hoang Lam",
  "age": 21,
  "role": "Trainee",
  "year": "1/1/2023",
  "education": "Bachelor"
}

###
POST http://localhost:5001/api/v1/staff/courses/create
Content-Type: application/json

{
  "name": "Application Development",
  "description": "No description",
  "categoryName": "IT"
}

###
POST http://localhost:5001/api/v1/staff/courses/create
Content-Type: application/json

{
  "name": "Economic Law",
  "description": "No description",
  "categoryName": "Business"
}

###
POST http://localhost:5001/api/v1/staff/categories/create
Content-Type: application/json

{
  "name": "IT",
  "description": "This is subject for student who have passion with IT"
}

###
POST http://localhost:5001/api/v1/staff/categories/create
Content-Type: application/json

{
  "name": "Business",
  "description": "This is subject for student who have passion with Biz"
}

###

DELETE http://localhost:5001/api/v1/staff/classes/delete/4

###
POST http://localhost:5001/api/v1/staff/classes/create
Content-Type: application/json

{
  "courseName": "Economic Law",
  "trainerID": "8a89593a7d5cf903d72cd9c46e41f623",
  "name": "GBD0805"
}

###
DELETE http://localhost:5001/api/v1/staff/classes/delete/13

###
POST http://localhost:5001/api/v1/staff/classes/create
Content-Type: application/json

{
  "courseName": "Application Development",
  "trainerID": "3678206b78358c55651e76a83aa2d704",
  "name": "GCD0806"
}


###
GET http://localhost:5001/api/v1/trainee/course/friends/Economic%20Law

###
GET http://localhost:5001/api/v1/trainee/course/friends/Application%20Development

###
POST http://localhost:5001/api/v1/staff/classes/trainee
Content-Type: application/json

{
  "className": "GBD0805",
  "traineeID": "72e98023a5f700c413ce7c59d5e2f0b7"
}

###
GET http://localhost:5001/api/v1/staff/trainee/search/?name=Nguyen%20Hoang%20Lam&age=21

###
PUT http://localhost:5001/api/v1/staff/trainee/update
Content-Type: application/json

{
  "oldData": {
    "fullname": "Lam Emilie",
    "age": 20
  },

  "newData": {
    "fullname": "Nguyen Hoang Lam",
    "age": 21,
    "email": "nguyenhoanglam.emilie@gmail.com"
  }
}
###

DELETE http://localhost:5001/api/v1/staff/classes/trainee/delete
Content-Type: application/json

{
  "name": "Nguyen Hoang Lam",
  "age": 21,
  "className": "GCD0806"
}

###
GET http://localhost:5001/api/v1/staff/classes

###
PUT http://localhost:5001/api/v1/staff/classes/trainer/assign/da25fa19467b04b06927973e7abeb673/GCD0806