GET http://localhost:5001/api/staff/courses

###
POST  http://localhost:5001/api/staff/auth/login
Content-Type: application/json

{
  "email": "vinhhn3@fpt.edu.vn",
  "password": "ILoveMyWife"
}

###
POST http://localhost:5001/api/staff/auth/register
Content-Type: application/json

{
  "email": "vinhhn3@fpt.edu.vn",
  "password": "ILoveMyWife",
  "fullname": "Hoang Nhu Vinh",
  "role": "Trainer",
  "specialty": "IT and Development"
}


###
POST http://localhost:5001/api/staff/auth/register
Content-Type: application/json

{
  "email": "ngotantu12@gmail.com",
  "password": "hehedontbeshilly",
  "fullname": "Ngo Tan Tu",
  "role": "Trainee",
  "year": "1/1/2023",
  "education": "Bachelor"
}

###
POST http://localhost:5001/api/staff/courses/create
Content-Type: application/json

{
  "name": "Cloud Computing",
  "description": "No description",
  "categoryName": "IT"
}

###

POST http://localhost:5001/api/staff/categories/create
Content-Type: application/json

{
  "name": "IT",
  "description": "This is subject for student who have passion with IT"
}

###

DELETE http://localhost:5001/api/staff/classes/delete/4

###
POST http://localhost:5001/api/staff/classes/create
Content-Type: application/json

{
  "courseName": "Cloud Computing",
  "trainerID": "1b42d567dccd08d98bbe39924bceaff2",
  "name": "GCD0807"
}


###
GET http://localhost:5001/api/trainee/course/friends

